### ISSUE TITLE
Watch command does not watch included files

### ISSUE THREAD

**Issue by 7dJx1qP** [Tetrax-10/stash-plugin-builder#2]
My plugin uses a python script and I've added the file to the settings.yml:
```
include: # include external files
    - ./src/myhook.py
```
I see that `npm run watch` will copy the file when I first run it, but it doesn't monitor this file for changes.

**Comment by Tetrax-10** [comment]
`stash-plugin-builder` won't watch external files as they aren't part of the main UI part. esbuild cant watch/compile python files

**Comment by 7dJx1qP** [comment]
ok I set up my own watch command for python files using the `copy-and-watch` npm package

**Comment by Tetrax-10** [comment]
In future I have planned to support python plugins. Then I will prob implement watch for external files

**Comment by Tetrax-10** [comment]
Done, now `stash-plugin-builder` can watch external files. 1b2079e
